#[package]
#name = "E2EE"
#version = "0.1.0"
#authors = ["Bean"]
#edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[workspace]
members = ["curve-crypto", "capi", "jniapi", "rust"]